/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Default: typeof import('./src/layouts/Default.vue')['default']
    Fullscreen: typeof import('./src/layouts/fullscreen.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
