import eslint from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import vuePlugin from "eslint-plugin-vue";
import globals from "globals";
import tseslint from "typescript-eslint";

// Auto-import globals generated by unplugin-auto-import
import autoImportGlobals from "./.eslintrc-auto-import.json" with { type: "json" };

export default tseslint.config(
    // Files to ignore
    {
        ignores: ["*.d.ts", "dist/**", "coverage/**"],
    },

    // Core ESLint + Vue + TS config
    {
        files: ["**/*.{ts,vue}"],

        extends: [
            eslint.configs.recommended,
            ...tseslint.configs.recommended,
            ...vuePlugin.configs["flat/recommended"],
        ],

        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                ...globals.browser,
                ...autoImportGlobals.globals,
            },
            parserOptions: {
                parser: tseslint.parser,
                extraFileExtensions: [".vue"],
            },
        },

        rules: {
            // -----------------------------------
            // Vue rules
            // -----------------------------------
            "vue/no-unused-vars": "error",
            "vue/multi-word-component-names": "off",
            "vue/no-irregular-whitespace": "error",
            "vue/template-curly-spacing": "error",

            // -----------------------------------
            // Style rules
            // -----------------------------------
            "comma-spacing": ["error", { before: false, after: true }],
            "key-spacing": ["error", { afterColon: true }],
            indent: ["error", 2],
            "comma-dangle": ["error", "always-multiline"],
            "object-curly-spacing": ["error", "always"],
            camelcase: "error",
            semi: ["error", "never"],
            "arrow-parens": ["error", "as-needed"],
            "newline-before-return": "error",

            // Comments spacing
            "lines-around-comment": [
                "error",
                {
                    beforeBlockComment: true,
                    beforeLineComment: true,
                    allowBlockStart: true,
                    allowClassStart: true,
                    allowObjectStart: true,
                    allowArrayStart: true,
                    ignorePattern: "!SECTION",
                },
            ],

            // Arrays formatting
            "array-element-newline": ["error", "consistent"],
            "array-bracket-newline": ["error", "consistent"],

            // -----------------------------------
            // TypeScript rules
            // -----------------------------------
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    varsIgnorePattern: "^_+$",
                    argsIgnorePattern: "^_+$",
                },
            ],
        },

        // For imports (Vue + TS)
        settings: {
            "import/resolver": {
                node: true,
                typescript: {},
            },
        },
    },

    // Disable formatting rules that conflict with Prettier
    eslintConfigPrettier,
);
